name: pull_request-test
on:
  pull_request:
    types:
    - opened
    - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/rp/go
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
    - name: Check out source
      uses: actions/checkout@v1
      with:
        path: go/src/github.com/jim-minter/rp
    - name: Test
      run: |
        set -x

        go generate ./...
        go build ./...
        go test ./...

        [[ -z "$(git status -s)" ]]
